services:
  mysql:
    image: mysql:latest
    container_name: knowledge_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: knowledge
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/val/lib/mysql
    networks:
      - knowledge

  ollama:
    image: ollama/ollama:latest
    container_name: knowledge_ollama
    ports:
      - "11434:11434" # Default port for Ollama
    volumes:
      - ./entrypoint.sh:/entrypoint.sh # pull model script
      - ./ollama/models:/root/.ollama/models # model cache
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: always
    networks:
      - knowledge

networks:
  knowledge:
    driver: bridge
